baseURL = "https://bplace.netlify.com/"
languageCode = "en-us"
title = "Timer | Responsive Multipurpose Bootstrap Hugo Template"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "Service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "Gallery"
        url     = "gallery"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Airspace Hugo theme"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "we are beoplace, we are"
        description = "between us we have many years experience, too many to contemplate, this is our forum."
        btn     = true
        btnText = "Download More"
        btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "architects"
        [[params.banner.flipText]]
            title   = "DEVELOPERs"
        [[params.banner.flipText]]
            title   = "curious"
        [[params.banner.flipText]]
            title   = "ecological"
        [[params.banner.flipText]]
            title   = "thinkers"
        [[params.banner.flipText]]
            title   = "builders"
        [[params.banner.flipText]]
            title   = "urbanists"
        [[params.banner.flipText]]
            title   = "creative"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Hello, Iâ€™m a UI/UX Designer & Front End Developer from Victoria, Australia. I hold a master degree of Web Design from the World University.And scrambled it to make a type specimen book. It has survived not only five centuries. <br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
        image   = "images/about/about.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Contact with me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    [params.footer]
        [[params.footer.socialIcon]]
            icon = "ion-social-facebook"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-instagram"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-linkedin"
            url = "#"
